// Supabase configuration
// Import from the autogenerated info.tsx file
export { projectId, publicAnonKey } from './info.tsx';

// Construct URL from project ID
import { projectId } from './info.tsx';
export const supabaseUrl = `https://${projectId}.supabase.co`;

// Export a helper to check if Supabase is properly configured
import { publicAnonKey } from './info.tsx';
export const isSupabaseConfigured = () => {
  return !!(projectId && publicAnonKey && projectId !== '' && publicAnonKey !== '');
};